version: "3"
 
services:
  next-app:
    build:
      context: ./next-app
      dockerfile: prod.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 2043
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bob.rule=Host(`uqbn.co.za`)"
      - "traefik.http.routers.bob.entrypoints=websecure"
      - "traefik.http.routers.bob.tls.certResolver=letsencrypt"
      - "traefik.http.services.bob.loadbalancer.server.port=2043"
networks:
  dokploy-network:
    external: true
